'------------------------------------------------------------------------------
' <auto-generated>
'    此代码是根据模板生成的。
'
'    手动更改此文件可能会导致应用程序中发生异常行为。
'    如果重新生成代码，则将覆盖对此文件的手动更改。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class sysInfo
    Public Property ID As Integer
    Public Property companyName As String
    Public Property sysName As String
    Public Property sysVersion As String
    Public Property sysKey As String
    Public Property sysLicence As String
    Public Property sysCreateTime As Nullable(Of Date)
    Public Property sysDeadTime As Nullable(Of Date)
    Public Property MaxUser As Nullable(Of Integer)
    Public Property sharePath As String
    Public Property remark As String

End Class
