'------------------------------------------------------------------------------
' <auto-generated>
'    此代码是根据模板生成的。
'
'    手动更改此文件可能会导致应用程序中发生异常行为。
'    如果重新生成代码，则将覆盖对此文件的手动更改。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class 用户表
    Public Property ID As Integer
    Public Property 用户名 As String
    Public Property 用户姓名 As String
    Public Property 用户密码 As String
    Public Property 用户权限 As Nullable(Of Integer)
    Public Property 上次登录时间 As Nullable(Of Date)
    Public Property 备注 As String

End Class
